### ISSUE TITLE
Switch branch during a dvc execution - concurrency

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#443] opened 2018-01-27 10:10 UTC
DVC uses a `.dvc/lock` to prevent a parallel execution and concurrency issues. However, DVC does not lock Git from changing state (changing branch for example). This creates potential concurrency issues.

Additional investigation is needed.

**Comment by dmpetrov** [comment] 2018-01-28 08:17
Does Git's create any external lockers? Can we use them?

**Comment by villasv** [comment] 2018-01-31 15:36
If you somehow manage to force each branch to have diverging `.dvc/lock`, then switching branch will be naturally blocked because it would result in conflicting changes with git. But that's not a fully friendly and explicit way to block it, as the user might simply use `git stash` and change branches anyway.

One way to be more explicit is to inject a git hook that checks for `.dvc/lock` before checkout and prevents it with a friendly message.

**Comment by dmpetrov** [comment] 2018-02-01 06:58
Right, the first approach not "friendly". However, some tricks might help to improve that - an investigation is needed.

Git hook - this solution is not general enough since hooks are not transferable by `git push\pull`. So, you will need to create the hooks for each `git clone`.

**Comment by efiop** [comment] 2018-02-01 14:10
Again, this is a problem for some very specific scenarios, that other tools like Makefile don't even bother solving. And I think that we too should not bother with it, at least in a core project.

**Comment by villasv** [comment] 2018-02-01 17:36
> Git hook - this solution is not general enough since hooks are not transferable by git push\pull. So, you will need to create the hooks for each git clone.

Running dvc commands could automatically check if all hooks are properly placed, but that's a little bit of overhead.

**Comment by dmpetrov** [comment] 2018-02-02 09:01
@villasv I meant that your git hook won't be available for people who clone your repo. Git hook is like your local alias.

@efiop brings a good point about Makefile. And even if Git lock file exists there is no guaranty that other code version control systems have that (we have plans to support not only Git).

I'll close this if there are no objections.

**Comment by villasv** [comment] 2018-02-02 11:53
> I meant that your git hook won't be available for people who clone your repo. Git hook is like your local alias.

I know, but if DVC silently checks and installs for each clone it should cover most use cases, including this one. But you two provably have discussed using git hooks extensively so I won't insist.

**Comment by dmpetrov** [comment] 2018-02-03 06:41
@villasv Unfortunately, DVC cannot silently check `git clone` without another hook :). The only thing we can do is to create a hook during `dvc init`. But each new repository (`git clone`) still won't have any hooks. Git is quite "traditional" from the hooks point of view.

I'm sorry that part of our discussions happens offline. We should talk more online or at least publish our ideas and conclusions as issues or docs.

**Comment by villasv** [comment] 2018-02-03 11:05
> But each new repository (git clone) still won't have any hooks. Git is quite "traditional" from the hooks point of view.

Yes, and because of that hooks will not cover all cases. It would cover this one. See, in order to have this concurrency issue you would need to issue a `dvc` command that creates the `.dvc/lock`. If that command created/checked for a checkout hook as well, the issue is solved.

**Comment by efiop** [comment] 2018-02-03 12:58
@villasv we have considered doing so. These are some of the problems I have with it:
1)everyone uses his own(or unique to the team/company) hooks

**Comment by efiop** [comment] 2018-02-03 13:24
@villasv You are absolutely right about that. However, there are some vague issues, which, at least for now, make us avoid using git hooks, leaving the ability to use them in the future.
1) we want to avoid messing around with source control system of the user so that we don't lock onto any specific systems and allow dvc to be used with or without scm. Thus, we want to avoid using git hooks if possible, as it will create behavior differences for users that are using different or no scm systems;
2) everyone uses git hooks in different ways that are specific to the user/team/company and we would rather not mess around with those(even in basic ways such as wrapping) for now and just leave the ability to do so in the future;
3) explicit is almost always better than implicit and git hooks operate implicitly, which creates a bad precedent;

**Comment by villasv** [comment] 2018-02-03 14:37
I agree to some degree with all points, specially 3 and to a lesser extent with 1. Like I said before, I imagine that you two probably spent a few hours discussing git hooks already and so wouldn't push too much on it - I was just explaining how in my POV it would solve this particular issue.

I believe you could close the issue as wontfix and simply warn users to not change the working tree during dvc commands.

> Are you at FOSDEM by any chance? :)

Unfortunately not. Will you be presenting DVC there by any chance? I've been recommending DVC word of mouth here and there, a live presentation would be great material.

**Comment by efiop** [comment] 2018-02-03 16:31
@villasv 
We genuinely appreciate your feedback and input, thank you!

No, we will not present DVC at FOSDEM yet. I am at the FOSDEM right now and was simply wondering if you are here as well :)

**Closed** 2018-02-03 16:32 UTC
Labels: bug, question
