### ISSUE TITLE
Consistently getting broken pipe when syncing (uploading) large file

### ISSUE THREAD

**Issue by ophiry** [dataversioncontrol/dvc#100] opened 2017-06-25 08:14 UTC
traceback (most recent call last):
 ```
 File "/Users/ophir/anaconda3/envs/p2/bin/dvc", line 11, in <module>
    sys.exit(main())
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/dvc/main.py", line 63, in main
    Runtime.run(CmdDataSync)
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/dvc/runtime.py", line 41, in run
    sys.exit(instance.run())
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/site-packages/dvc/command/data_sync.py", line 47, in run
    pool.map(cloud.sync, targets)
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/ophir/anaconda3/envs/p2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
socket.error: [Errno 32] Broken pipe
```

p.s. 
is syncing the file manually using the aws cli a viable workaround, or are there other things done during the sync (updating status file or something similar)

**Comment by efiop** [comment] 2017-06-25 23:47
Hi!

Thank you for reporting this to us. Could you please share some additional info? This dvc 8.5.0 from pip, right? How big of a file are we talking about?

There is additional info(i.e. hash) being used during the sync, so using aws cli directly in a naive way probably wouldn't work =(.

**Comment by ophiry** [comment] 2017-06-26 05:03
i's indeed 0.85 from pip
the file is ~8GB

copying the file didn't work, even though I copied the file from the cache directory (that includes the hash as part of the name)

**Comment by efiop** [comment] 2017-06-28 00:23
Hm... I tried to sync 20G files and it worked just fine. @ophiry could you please try upstream dvc? I.e. clone it somewhere and do "pip uninstall dvc && ./build_package.sh && pip install dist/dvc-0.8.5.tar.gz".

**Comment by dmpetrov** [comment] 2017-06-28 04:17
@efiop it looks like concurrency issue, not file size.

**Comment by dmpetrov** [comment] 2017-06-28 08:17
Closed by 059fcc0
Package version: 0.8.6

@ophiry please upload the package `pip -U dvc`
Btw... thank you for reporting the bug.

**Comment by efiop** [comment] 2017-06-28 08:22
@dmpetrov Were you able to reproduce?

**Comment by dmpetrov** [comment] 2017-06-28 08:30
Yes, it was easy to reproduce on Mac. The issue was related to zero file size `data/empty`.
I guess Mac OS has a special version of the multiprocessing library.

**Comment by efiop** [comment] 2017-06-28 08:32
Oh, those Macs... Thanks for the info.

**Comment by ophiry** [comment] 2017-06-29 16:28
still have the same problem after upgrading to 0.8.6

**Comment by dmpetrov** [comment] 2017-06-29 16:48
Wow.
Thank you for letting us know. Reopening...

**Comment by efiop** [comment] 2017-07-02 23:27
@ophiry  As we've discovered with @dmpetrov , the issue looks to be related to network connection loss when your laptop goes into standby mode while syncing big files. I just merged a temporary fix https://github.com/dataversioncontrol/dvc/pull/109 that will at least notify us if something goes wrong, but a proper fix would be to implement partial download/upload as huge files are not something unusual for dvc scenarios and it would be great if we could continue download/upload from where we've left: https://github.com/dataversioncontrol/dvc/issues/108.

@ophiry could you please try out new dvc once again so we could confirm that the issue is indeed caused by lost network connection? Thank you.

**Comment by ophiry** [comment] 2017-07-10 05:15
this is the latest log (install from master version)
```
Checksum miss-match. Re-uploading is required.
.cache/quality_model/training/rdb.lmdb/data.mdb_ded3948489c: 0.0B transferred out of 8.6GB
(1/10): [                                        ] 0% data.mdb_ded3948489c.cache/quality_model/training/rdb.lmdb/data.mdb_ded3948489c: 0.0B transferred out of 8.6GB
(1/10): [                                        ] 0% data.mdb_ded3948489c.cache/quality_model/training/rdb.lmdb/data.mdb_ded3948489c: 0.0B transferred out of 8.6GB
(1/10): [                                        ] 0% data.mdb_ded3948489c.cache/quality_model/training/rdb.lmdb/data.mdb_ded3948489c: 0.0B transferred out of 8.6GB
(1/10): [                                        ] 0% data.mdb_ded3948489c.cache/quality_model/training/rdb.lmdb/data.mdb_ded3948489c: 0.0B transferred out of 8.6GB
(1/10): [                                        ] 0% data.mdb_ded3948489c.cache/quality_model/training/rdb.lmdb/data.mdb_ded3948489c: 0.0B transferred out of 8.6GB
(1/10): [                                        ] 0% data.mdb_ded3948489c.cache/quality_model/training/rdb.lmdb/data.mdb_ded3948489c: 0.0B transferred out of 8.6GB
(1/10): [                                        ] 0% data.mdb_ded3948489cFailed to upload ".cache/quality_model/training/rdb.lmdb/data.mdb_ded3948489c": [Errno 32] Broken pipe
```

**Comment by dmpetrov** [comment] 2017-07-10 21:15
@ophiry could you please clarify. Did your laptop fell into sleep mode during the downloading? It looks like the issue happens after sleep mode (most likely when network turns on for 5+ minutes).

If not - when this issue happened: right after `dvc sync ...` or in 10/20 minutes?

**Comment by ophiry** [comment] 2017-07-11 19:42
it wasn't during sleep, it was a few minutes after the sync started.
the strange thing is that from the progress bar there was no data transferred at all
communicating with s3 through the aws cli worked

**Comment by efiop** [comment] 2017-08-06 16:12
@ophiry Hi! Sorry for a delay, I'm back on this issue again.
I suspect this issue: https://github.com/boto/boto/issues/621 to be the cause. Could you please share your region from dvc.conf and also your boto version? Thanks!

**Comment by efiop** [comment] 2017-08-06 17:22
Hi @ophiry ! Sorry for such a long delay, I'm back on this issue again.
Unfortunately, I'm still not able to reproduce it, but after a bit for googling, I found https://github.com/boto/boto/issues/621 which sounds very similar, but we actually do explicitly specify host when creating S3Connection so this bug should not occur. However, I see that we construct host as 's3.%s' and not as 's3-%s'(notice the '-' instead of '.') which actually doesn't always formally apply as one could see in http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region(i.e. us-west-2 is only listed with s3-us-west-2 and without s3.us-west-2, though both links are ping-able). What is your s3 region from dvc.conf?

**Comment by ophiry** [comment] 2017-08-06 19:45
the region is us-east-1, which is the region of the bucket

not sure it's relevant, but the issue is with an lmdb file

**Comment by efiop** [comment] 2017-08-20 11:00
Sorry again for such a delay. I managed to reproduce this issue(only on Mac, other platforms work fine) for files that are >5G(tested on 8G and 4G, the former reproduced the issue and the latter was uploaded just fine), which makes sense as aws actually mentions this limitation in their docs, but the strange part is that on Linux this limit doesn't seem to result in anything). So this issue should be fixed with https://github.com/dataversioncontrol/dvc/issues/163. I'm working on implementing it right now and expect to deliver it in 24h hopefully =). Thank you for your patience.

**Comment by efiop** [comment] 2017-08-20 13:40
@ophiry I merged #178. Tested it on my mac, everything seems fine now. Could you confirm that it works for you too? Also note that you can now use 'dvc push data/DATA' command for pushing data to the cloud ;) .  Feel free to reopen this issue if anything is still wrong.

**Comment by efiop** [comment] 2017-08-20 13:51
Oh, actually, just a second. Seems like I broke it.

**Comment by efiop** [comment] 2017-08-20 14:57
Looks like md5 got screwed. Reverted #178 . Reopening this issue for now.

**Comment by ophiry** [comment] 2017-08-20 15:03
do you mean that etag doesn't contain now the md5 of the full file?
A possible workaround is to store the md5 in git (in the state file) when importing a file, and use this value as the "ground truth" for md5

**Comment by efiop** [comment] 2017-08-20 15:09
Yes, precisely, multipart uploads add a giant hustle with the md5.

That's a brilliant idea! Thank you! I will implement it shortly.

**Comment by efiop** [comment] 2017-08-20 15:29
Actually, the problem with storing md5 in state file is that even thought it will help us determine if local data has changed, we will still have to download data from the cloud to verify it, because getting md5 of a multi-part object stored in the cloud is still a hustle.

A better solution would be to store original md5 in metadata when uploading file, so we have an easy access to it without actually having to download full file. Ok, I will try this out and will get back soon =)

Thank you!

**Closed** 2017-08-20 16:23 UTC
Labels: bug

**Comment by efiop** [comment] 2017-08-20 16:26
Right, storing md5 in metadata worked out great. We should be set now.

Feel free to reopen this issue if anything is still wrong.
