### ISSUE TITLE
Modified data file error message

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#117] opened 2017-07-22 09:13 UTC
```[dvc-git] Commit all changed files before running reproducible command. Changed files:
?? data/matrix-train.p```

We probably need a better error message for a case when a data file was changed. Something like: please revert data file to a previous checked-ined version `git checkout data/matrix-train.p`.

**Comment by efiop** [comment] 2017-09-03 12:15
Looks like this error was caught during the debugging, as GitWrapper.is_ready_to_go actually has a meaningful msg "'[dvc-git] Commit all changed files before running reproducible command. Changed files:'". Closing this issue for now.

**Closed by efiop** 2017-09-03 12:15 UTC
Labels: enhancement
