### ISSUE TITLE
dvc cache push is slow for many files

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#497] opened 2018-03-01 15:29 UTC
Pushing 1.5Gb dvc repository with 8K small data files takes more than 6 hours inside AWS.

**Comment by dmpetrov** [comment] 2018-03-01 15:45
There were 83K very small files, not 8K.
So, this issue priority is not too high.

**Comment by dmpetrov** [comment] 2018-03-01 16:54
Data directories are big part of this issue since DVC mirrors the directory structure and creates a corresponded file for each file from the dir.

@efiop is there a way to create a single file to store the data directory structure?

**Comment by efiop** [comment] 2018-03-01 21:16
I have a few thoughts on the alternative ways to store dirs. I'll take a closer look soon.

**Comment by efiop** [comment] 2018-03-02 01:21
Actually, the main problem here is that we don't reuse aws connections and instead establish a new one every time we push/pull a file. This is a known issue. I am already working on it.

**Comment by efiop** [comment] 2018-03-02 14:35
Ok, found the issue. Cached dirs are currently processed in 1 thread in cloud logic code. Already working on fixing that.

**Comment by efiop** [comment] 2018-03-03 02:38
Managed to speed up x7 times for a few hundred small files with https://github.com/dataversioncontrol/dvc/pull/504 . Still, dvc is not really optimized for an extreme number of small files, so you might want to consider packing those into tar or something. Closing for now.

**Closed by efiop** 2018-03-03 02:38 UTC
Labels: bug

**Comment by dmpetrov** [comment] 2018-03-03 02:40
x7 is awesome! Thank you.

Yeah, we need to invent some file packing tricks like Git does.

**Comment by mazzma12** [comment] 2019-10-02 11:43
Note that the group between users has to be a primary group and not a secondary. This can be changed by running : `usermod -g groupName $USER`

**Comment by efiop** [comment] 2019-10-02 12:55
@mazzma12 Looks like you've mistaken dvc and dvc.org repos :) You've meant to link https://github.com/iterative/dvc.org/issues/497 . I'll copy your comment there. Thanks!

**Comment by stiv-yakovenko** [comment] 2021-04-05 05:28
I have the same problem. **dvc push** takes about 10 minutes to finish:

  0% Querying cache in 'gdrive://root/dvc_root/rv_data'|       |38641/? [05:39<00:00, 110.39file/s]

To reproduce you can download 2018-8-21_2018-8-27.zip (few GB) https://databank.illinois.edu/datasets/IDB-3671567, unzip and add to DVC repository.
